DROP TABLE IF EXISTS EXPENSE;
CREATE TABLE EXPENSE (
    ID INT IDENTITY PRIMARY KEY, 
    NAME VARCHAR(255) NOT NULL, 
    DESCRIPTION VARCHAR(255) NOT NULL,
    DATE_REGISTER DATETIME,
    AMOUNT MONEY,
    TAGS VARCHAR(255)
);

/*INSERT INTO EXPENSE (NAME, DESCRIPTION, DATE_REGISTER, AMOUNT, TAGS) VALUES ('Azevedo','Notebook para Java',GETDATE(), 4999.90,'rápido, incrível,estupendo');*/